package br.com.chaletSmart.domain.register.enums

enum class SwitcherType(val consumptionType: String) {
    CHALET_PRINCIPAL_ILUMINACAO_QUARTO("CHALET_PRINCIPAL_ILUMINACAO_QUARTO"),
    CHALET_PRINCIPAL_ILUMINACAO_COZINHA("CHALET_PRINCIPAL_ILUMINACAO_COZINHA"),
    CHALET_PRINCIPAL_ILUMINACAO_SALA("CHALET_PRINCIPAL_ILUMINACAO_SALA"),
    CHALET_PRINCIPAL_ILUMINACAO_BANHEIRO("CHALET_PRINCIPAL_ILUMINACAO_BANHEIRO"),
    CHALET_PRINCIPAL_ILUMINACAO_QUINTAL("CHALET_PRINCIPAL_ILUMINACAO_QUINTAL"),
    CHALET_PRINCIPAL_ILUMINACAO_RELE_EXTERNO("CHALET_PRINCIPAL_ILUMINACAO_RELE_EXTERNO"),
    CHALET_2_ILUMINACAO("CHALET_2_ILUMINACAO"),
    CHALET_3_ILUMINACAO("CHALET_3_ILUMINACAO"),
    CHALET_4_ILUMINACAO("CHALET_4_ILUMINACAO"),
    CHALET_5_ILUMINACAO("CHALET_5_ILUMINACAO")
}
