micronaut:
  application:
    name: apiChaletSmart
  server:
    cors:
      enabled: true

datasources:
  default:
    dialect: POSTGRES
    driverClassName: org.postgresql.Driver
    password: secret
    schema-generate: CREATE_DROP
    url: jdbc:postgresql://localhost:5432/chaletSmart
    username: postgres

jpa:
  default:
    compile-time-hibernate-proxies: true
    entity-scan:
      packages: 'br.com.chaletSmart.domain.register.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true